# ======================================
# TreeMaintainer Configuration
# ======================================
# Plugin Version: ${project.version}
# 
# This configuration file controls all aspects of the TreeMaintainer plugin.
# For support or questions, visit: https://github.com/McKenzieJDan/TreeMaintainer

# ======================================
# General Settings
# ======================================

# Master switch to enable or disable the plugin
enabled: true

# ======================================
# Tree Maintenance Settings
# ======================================

# Auto-replant settings
replanting:
  # Enable automatic sapling replanting
  enabled: true
  
  # Delay in ticks before replanting (20 ticks = 1 second)
  delay: 5

# Floating tree parts cleanup
cleanup:
  # Enable removal of floating logs and leaves
  enabled: true
  
  # Maximum distance to check for connected blocks
  max-distance: 10

# Tool settings
tools:
  # Only trigger the plugin when trees are cut with axes
  require-axe: true
  
  # Respect tool efficiency enchantments
  respect-efficiency: true

# ======================================
# Tree Type Settings
# ======================================

# Enable/disable specific tree types
tree-types:
  oak: true
  spruce: true
  birch: true
  acacia: true
  dark_oak: true
  mangrove: true
  cherry: true
  jungle: false

# ======================================
# Update Checker Settings
# ======================================

# Enable the update checker
update-checker:
  # Enable or disable the update checker
  enabled: true
  
  # The SpigotMC resource ID for the plugin
  # https://www.spigotmc.org/resources/treemaintainer.122862/
  resource-id: 122862
  
  # Notify admins when they join if an update is available
  notify-admins: true

# ======================================
# Advanced Settings
# ======================================

# Debug mode - when enabled, additional information will be printed to the console
# Only enable this when troubleshooting issues
debug: false 